server:
  port: 0
spring:
  application:
    name: PhotoAppAPIUsers
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  datasource:
    generateUniqueName: false
    name: photo_app
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${instanceId:${random.value}}
gateway:
  ip: 10.0.0.13
token:
  expiration_time: 36000000
  secret: djhfjdjfdkfkdifkkjdsyfidu