server:
  port: 9013
spring:
  application:
    name: PhotoAppAPIUsers
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    generateUniqueName: false
    name: photo_app
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8012
  cloud:
    config:
      name: PhotoAppApiConfigServer
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${instanceId:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: beans,health,mappings,httpexchanges