server:
  port: 0
spring:
  application:
    name: PhotoAppAPIUsers
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
  devtools:
    restart:
      enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${instanceId:${random.value}}