server:
  port: 9013
spring:
  application:
    name: PhotoAppAPIUsers
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    generateUniqueName: false
    name: photo_app
  h2:
    console:
      enabled: true
      settings:
        webAllowOthers: true
  devtools:
    restart:
      enabled: true
  config:
    import: optional:configserver:http://localhost:8012
  cloud:
    config:
      name: user-ws
    gateway:
      discovery:
        locator:
          enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    instanceId: ${spring.application.name}:${instanceId:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: *
  endpoint:
    health:
      enabled: true
      showDetails: always
  health:
    circuitbreakers:
      enabled: true
logging:
  level:
    com:
      example:
        appdevelopersblog:
          PhotoAppAPIUsers:
            data:
              AlbumsServiceClient: DEBUG
resilience4j:
  circuitbreaker:
    instances:
      albums-ws:
        failure-rate-threshold: 50
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10000ms
        sliding-window-type: COUNT_BASED
        sliding-window-size: 2
        minimum-number-of-calls: 1
        event-consumer-buffer-size: 10
